server:
  port: 18083

spring:
   application:
     name: canal

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enable: true

# hystrix配置
hystrix:
  command:
    default:
      execution:
        timeout:
          enable: true # 如果enable设置为false，则请求超时交给ribbon控制
        isolation:
          strategy: SEMAPHORE

# Canal 配置
canal:
  client:
    instances:
      example:
        host: 192.168.0.186
        port: 11111
